### ISSUE TITLE
@haruyama

### ISSUE THREAD

**Issue by haruyama** [syossan27/rejected-us-jp#2]
経歴: http://seesaawiki.jp/w/haruyama_seigo/d/%bf%a6%cc%b3%b7%d0%ce%f2

2008年や2013年にも就職活動しており落ちた会社はありますが, とりあえず 2011年のときのものを
## 2011年に落ちた会社
- リクルート: メディアテクノロジーラボ(当時)をリクルートエージェント経由で受けたが, 1回目の面接が人事で会社に合わない人と判断され終了
- ライブドア: CTOを紹介してもらって面談したあと普通の採用ルートから応募. 1回目の面接で不採用. エージェントを経由していないので理由は不明.
- ドワンゴ: エージェント経由で技術部長クラス2名と面談したが, エージェントの紹介が酷くまた話も盛り上らず終了
- もう存在しない小さい会社: 報酬面で折り合いがつかず

**Comment by syossan27** [comment]
@haruyama 
ありがとうございます！
掲載するお名前ですが経歴に書かれている本名かハンドル名（haruyama）かどちらに致しましょうか？

**Comment by haruyama** [comment]
ハンドルでお願いします

**Comment by haruyama** [comment]
ページをみたら

```
黒木 俊太郎
@syunk38 
```

あとの方は上記のスタイルなんですね.

```
春山 征吾
@haruyama
```

でもいいです. もう作業してしまっていたらそのままで

**Comment by syossan27** [comment]
@haruyama 
それでは

```
春山 征吾
@haruyama
```

で掲載させて頂きます。
